name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore Flashcards
    - name: Build
      run: dotnet build Flashcards --no-restore
    - name: Test
      run: dotnet test Flashcards --no-build --verbosity normal
    - name: Publish
      run: dotnet publish Flashcards -c Release -o dotnetcorewebapp 
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: 'flashcards-project'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3bfdbad73f594578b34280ada1773c76 }}
        package: './dotnetcorewebapp' 
      
