name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore Flashcards
    - name: Build
      run: dotnet build Flashcards --no-restore
    - name: Test
      run: dotnet test Flashcards --no-build --verbosity normal
    - name: Publish
      run: dotnet publish Flashcards -c Release -o flashcards 
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
          app-name: ${{ env.flashcards-project }} # Replace with your app name
          publish-profile: ${{ secrets.AZURE }} # Define secret variable in repository settings as per action documentation
          package: '${{ env.flashcards-project }}/flashcards'

      
